name: "exo3 workflow"

on: push

env:
  VAR_FROM_WF: "varr"
jobs:
  Tests:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    env:
      VAR_FROM_JOB: "varrjob"
    runs-on: ubuntu-latest
    steps:
      - name: vartest
        env:
          VAR_FROM_STEP: "varrstep"
        run: |
          echo $VAR_FROM_WF
          echo $VAR_FROM_JOB
          echo $VAR_FROM_STEP
          echo $GITHUB_REF
      # - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
      # - run: npm install
      # - run: npm run test:ci
