name: "workflow exo1"

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: whoami
      - uses: actions/checkout@v4
      - run: mkdir tempdir
      - run: cat > tempdir/hi2.txt
      - run: ls -a -R
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -a -R
      
      
    
