name: "exo3 workflow"

on: push

# env:
#   VAR_FROM_WF: "varr"

jobs:
  CopScene:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.testout.outputs.VAROUT }}
      # output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: testout
        run: echo "VAROUT=CopScene" >> $GITHUB_OUTPUT
      # - id: step1
      #   run: echo "test=hello" >> "$GITHUB_OUTPUT"

  CopVideo:
    runs-on: ubuntu-latest
    steps:
      - run: echo CopVideo
  Detective:
    needs: [CopScene, CopVideo]
    runs-on: ubuntu-latest
    steps:
      - env:
          OUTPUT1: ${{needs.CopScene.outputs.output1}}
        run: echo "$OUTPUT1"
#   SWAT:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo SWAT


# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     # Map a step output to a job output
#     outputs:
#       output1: ${{ steps.step1.outputs.test }}
#       output2: ${{ steps.step2.outputs.test }}
#     steps:
#       - id: step1
#         run: echo "test=hello" >> "$GITHUB_OUTPUT"
#       - id: step2
#         run: echo "test=world" >> "$GITHUB_OUTPUT"
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - env:
#           OUTPUT1: ${{needs.job1.outputs.output1}}
#           OUTPUT2: ${{needs.job1.outputs.output2}}
#         run: echo "$OUTPUT1 $OUTPUT2"