name: "workflow exo1"

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: whoami
      - uses: actions/checkout@v4
      - run: mkdir tempdir
      - run: cat > tempdir/hi.txt
      - run: ls -a
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher WD
        run: pwd
      - run: ls -a -R
      - uses: actions/checkout@v4
      - run: cp hi.txt hi2.txt
      - run: echo "second step"
      - run: ls -a
      
      
    
