name: "exo4 workflow"

on:
  workflow_dispatch:
    inputs:
      nom_client:
        description: "Saisissez nom du client"
        required: true
      pizza:
        description: |
          Liste des pizzas au format JSON. Attention aux points importants:
            - Utilisez des guillemets doubles
            - Entourez la liste avec []
            Exemple: ["margherita","reine","calzone"]
        required: true
jobs:

  reception-commande:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Le policier examine la caisse enregistreuse
  cuisine:
    needs: reception-commande
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Le policier examine la caisse enregistreuse
  livraison:
    needs: cuisine
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Le policier examine la caisse enregistreuse
  reclamation:
    needs: livraison
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Le policier examine la caisse enregistreuse