name: "exo4 workflow"

on:
  workflow_dispatch:
    inputs:
      nom_client:
        description: "Saisissez nom du client"
        required: true
      pizzas:
        description: |
          Liste des pizzas au format JSON. Attention aux points importants:
            - Utilisez des guillemets doubles
            - Entourez la liste avec []
            Exemple: ["margherita","reine","calzone"]
        required: true
jobs:

  reception-commande:
    runs-on: ubuntu-latest
    outputs:
      pizzas: "${{ github.event.inputs.pizzas }}"
    steps:
      - run: echo "Bienvenue ${{ github.event.inputs.nom_client }}"
      - run: echo "Commande reçue, ${{ github.event.inputs.pizzas }}"
  cuisine:
    needs: reception-commande
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pizzas: ${{ fromJSON(needs.reception-commande.outputs.pizzas) }}
    
    steps:
      - run: echo "Cooking, ${{ matrix.pizzas }}"
  livraison:
    needs: cuisine
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Le policier examine la caisse enregistreuse"
  reclamation:
    needs: livraison
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Le policier examine la caisse enregistreuse"